# Generated by Django 5.2.1 on 2025-05-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verifiers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verifier",
            options={"ordering": ["name"]},
        ),
    ]
