# Generated by Django 5.2.1 on 2025-05-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verification_tasks", "0005_alter_verificationtask_expected_result"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verificationtask",
            options={"ordering": ["category", "name"]},
        ),
    ]
