# Generated by Django 5.2.1 on 2025-06-08 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification_tasks", "0006_alter_verificationtask_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="verification_tasks.verificationcategory",
                    ),
                ),
            ],
        ),
    ]
