# Generated by Django 5.2.1 on 2025-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification_tasks", "0007_verificationsubcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "patterns",
                    models.TextField(
                        default="",
                        help_text="Patterns to match verification tasks in this subcategory. Use regex-like syntax with '*' for wildcards.",
                    ),
                ),
                (
                    "subcategories",
                    models.ManyToManyField(
                        blank=True, to="verification_tasks.verificationsubcategory"
                    ),
                ),
            ],
        ),
    ]
