# Generated by Django 5.2.1 on 2025-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification_tasks", "0008_verificationset"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationtask",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subcategories of the verification task.",
                to="verification_tasks.verificationsubcategory",
            ),
        ),
    ]
